```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cool Docs"
theme = "docsy"

[params]
  description = "We specialize in helping startups build documentation processes using open source tools and a Docs-as-code methodology."
  author = "Cool Docs Team"
  logo = "/images/logo.png"
  favicon = "/images/favicon.ico"

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disabled = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
```