```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cool Docs"
theme = "docsy"

[params]
  description = "Bootstrap your docs team."
  logo = "/images/logo.png"
  favicon = "/images/favicon.ico"

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disabled = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```